/**
 * Crypto self-tests + cross-platform vector pinning.
 *
 * The byte-level expectations baked into this file MUST match those
 * in `Tests/SophonCryptoTests.swift` exactly. Drift in either side
 * fails the local suite immediately.
 *
 * Strategy:
 * - **Deterministic primitives** (HKDF, HMAC, ECDH) → pin expected
 *   output bytes as hex string constants. Same hex constants live
 *   in the Swift test file. Any divergence between the two impls
 *   surfaces as a hex mismatch, byte-for-byte.
 * - **Random primitives** (AES-GCM with random nonce) → round-trip
 *   only (encrypt own output, decrypt own output). Cross-platform
 *   AES-GCM correctness is a property of the algorithm; both Apple
 *   CryptoKit and Node `node:crypto` are NIST-validated, no need to
 *   manually pin nonce'd vectors at this stage. Real cross-platform
 *   integration test happens in Phase 3 when bridge-encrypted blobs
 *   actually land on iOS.
 */

import { describe, expect, it } from 'vitest'
import { Buffer } from 'node:buffer'
import {
  AES_KEY_BYTES,
  BLIND_INDEX_BYTES,
  MalformedEnvelopeError,
  NULL_SENTINEL,
  SYMM_VERSION_V1,
  UnsupportedVersionError,
  X25519_KEY_BYTES,
  blindIndex,
  decryptSymmetric,
  deriveBlindIndexKey,
  deriveBlobKey,
  deriveInstallKeyFromECDH,
  deriveSASFromECDH,
  encryptSymmetric,
  generateKeypair,
} from './crypto'

// ─── Fixed test inputs (mirrored verbatim in SophonCryptoTests.swift) ─

const FIXED_INSTALL_KEY_HEX =
  '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
// Both libsodium (iOS via swift-sodium) and tweetnacl (bridge) clamp
// internally per RFC 7748 on every scalarmult, so seeds can be raw —
// the post-HKDF derived keys still match byte-for-byte.
const FIXED_BRIDGE_SECRET_HEX =
  '1111111111111111111111111111111111111111111111111111111111111111'
const FIXED_BRIDGE_PUBLIC_HEX =
  '7b4e909bbe7ffe44c465a220037d608ee35897d31ef972f07f74892cb0f73f13'
const FIXED_IOS_SECRET_HEX =
  '2222222222222222222222222222222222222222222222222222222222222222'
const FIXED_IOS_PUBLIC_HEX =
  '0faa684ed28867b97f4a6a2dee5df8ce974e76b7018e3f22a1c4cf2678570f20'

// Expected outputs — generated by this very implementation. Pin them
// here and any drift trips a test. Swift test asserts the same hex.

const EXPECTED_BLOB_KEY_MESSAGES_ABC_HEX =
  '0e63257899b5f60d7bfde449cf46a92633c14aacc10e619b5c9485e6947464ec'
const EXPECTED_BLIND_IDX_KEY_HEX =
  '4502be12df6ca509e22785edb957f143250f5c78ad1ad0156157c68f28394b8e'
const EXPECTED_BLIND_IDX_AGENT_FILES_HEX = 'CC425Syg8HVCm_atfoI6lg'
const EXPECTED_INSTALL_FROM_ECDH_HEX =
  'aa52bee1cc39d680ba05ccb4cef8541b0c80f05f1fe4321cfcd34ff2478ff11a'
const EXPECTED_SAS_FROM_ECDH_HEX = 'e2fb1f8a'

const hex = (s: string) => Uint8Array.from(Buffer.from(s, 'hex'))
const toHex = (b: Uint8Array) => Buffer.from(b).toString('hex')

// ─── Symmetric AEAD ─────────────────────────────────────────────────

describe('encryptSymmetric / decryptSymmetric', () => {
  const key = hex(FIXED_INSTALL_KEY_HEX)

  it('round-trips a non-empty plaintext', () => {
    const plain = new TextEncoder().encode('hello sophon e2e')
    const ct = encryptSymmetric(plain, key)
    const out = decryptSymmetric(ct, key)
    expect(out).not.toBeNull()
    expect(new TextDecoder().decode(out!)).toBe('hello sophon e2e')
  })

  it('emits versioned envelope with expected layout', () => {
    const ct = encryptSymmetric(new TextEncoder().encode('x'), key)
    expect(ct[0]).toBe(SYMM_VERSION_V1)
    // 1 (version) + 12 (nonce) + 1 (ciphertext for 'x') + 16 (tag)
    expect(ct.length).toBe(1 + 12 + 1 + 16)
  })

  it('uses a fresh nonce per call (non-deterministic)', () => {
    const a = encryptSymmetric(new TextEncoder().encode('same'), key)
    const b = encryptSymmetric(new TextEncoder().encode('same'), key)
    // bytes 1..13 = nonce; if equal then we have a fixed-nonce bug
    expect(Buffer.from(a.slice(1, 13))).not.toEqual(Buffer.from(b.slice(1, 13)))
  })

  it('uses NULL_SENTINEL for empty plaintext', () => {
    const ct = encryptSymmetric(new Uint8Array(0), key)
    expect(ct.length).toBe(1)
    expect(ct[0]).toBe(NULL_SENTINEL)
    const out = decryptSymmetric(ct, key)
    expect(out).not.toBeNull()
    expect(out!.length).toBe(0)
  })

  it('returns null on AEAD failure (tampered byte)', () => {
    const ct = encryptSymmetric(new TextEncoder().encode('hi'), key)
    const tampered = new Uint8Array(ct)
    tampered[15] = (tampered[15] ?? 0) ^ 0xff
    expect(decryptSymmetric(tampered, key)).toBeNull()
  })

  it('returns null on AEAD failure (wrong key)', () => {
    const ct = encryptSymmetric(new TextEncoder().encode('hi'), key)
    const wrongKey = new Uint8Array(AES_KEY_BYTES)
    expect(decryptSymmetric(ct, wrongKey)).toBeNull()
  })

  it('throws UnsupportedVersionError on unknown version', () => {
    const ct = encryptSymmetric(new TextEncoder().encode('hi'), key)
    const bad = new Uint8Array(ct)
    bad[0] = 0x99
    expect(() => decryptSymmetric(bad, key)).toThrow(UnsupportedVersionError)
  })

  it('throws MalformedEnvelopeError on truncation', () => {
    const ct = encryptSymmetric(new TextEncoder().encode('hi'), key)
    expect(() => decryptSymmetric(ct.slice(0, 5), key)).toThrow(
      MalformedEnvelopeError,
    )
  })

  it('throws on bad key length', () => {
    expect(() =>
      encryptSymmetric(new Uint8Array(0), new Uint8Array(31)),
    ).toThrow(/bad key length/)
  })
})

// ─── KDF + blind index (cross-platform pinned) ──────────────────────

describe('deriveBlobKey', () => {
  it('matches the pinned hex for the canonical input pair', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const out = deriveBlobKey(installKey, 'messages/abc')
    expect(toHex(out)).toBe(EXPECTED_BLOB_KEY_MESSAGES_ABC_HEX)
  })

  it('is deterministic — same inputs → same key', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const a = deriveBlobKey(installKey, 'tasks/x/input')
    const b = deriveBlobKey(installKey, 'tasks/x/input')
    expect(toHex(a)).toBe(toHex(b))
  })

  it('domain-separates by path', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const a = deriveBlobKey(installKey, 'messages/abc')
    const b = deriveBlobKey(installKey, 'messages/xyz')
    expect(toHex(a)).not.toBe(toHex(b))
  })
})

describe('deriveBlindIndexKey + blindIndex', () => {
  it('matches the pinned hex for blind-index-key derivation', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const idxKey = deriveBlindIndexKey(installKey)
    expect(toHex(idxKey)).toBe(EXPECTED_BLIND_IDX_KEY_HEX)
  })

  it('matches the pinned hex for an agent-files blind index', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const idxKey = deriveBlindIndexKey(installKey)
    const idx = blindIndex(idxKey, 'agent_files', 'ses_abc', '/Users/foo/bar.swift')
    expect(idx).toBe(EXPECTED_BLIND_IDX_AGENT_FILES_HEX)
  })

  it('encodes to base64url with no padding (16 bytes → 22 chars)', () => {
    const installKey = hex(FIXED_INSTALL_KEY_HEX)
    const idxKey = deriveBlindIndexKey(installKey)
    const idx = blindIndex(idxKey, 'agent_files', 'ses_abc', '/x')
    expect(idx).toMatch(/^[A-Za-z0-9_-]{22}$/)
    expect(idx.length).toBe(22)
  })

  it('produces 16 raw bytes before encoding', () => {
    expect(BLIND_INDEX_BYTES).toBe(16)
  })
})

// ─── Pairing (ECDH) — cross-platform pinned ─────────────────────────

describe('deriveInstallKeyFromECDH + deriveSASFromECDH', () => {
  it('matches the pinned hex for install_key derived via ECDH', () => {
    const bridgeSec = hex(FIXED_BRIDGE_SECRET_HEX)
    const iosPub = hex(FIXED_IOS_PUBLIC_HEX)
    const out = deriveInstallKeyFromECDH(bridgeSec, iosPub)
    expect(toHex(out)).toBe(EXPECTED_INSTALL_FROM_ECDH_HEX)
  })

  it('is commutative across the pair (both ends derive same install_key)', () => {
    const bridgeSec = hex(FIXED_BRIDGE_SECRET_HEX)
    const bridgePub = hex(FIXED_BRIDGE_PUBLIC_HEX)
    const iosSec = hex(FIXED_IOS_SECRET_HEX)
    const iosPub = hex(FIXED_IOS_PUBLIC_HEX)
    const a = deriveInstallKeyFromECDH(bridgeSec, iosPub)
    const b = deriveInstallKeyFromECDH(iosSec, bridgePub)
    expect(toHex(a)).toBe(toHex(b))
  })

  it('matches the pinned hex for SAS derived via ECDH', () => {
    const bridgeSec = hex(FIXED_BRIDGE_SECRET_HEX)
    const iosPub = hex(FIXED_IOS_PUBLIC_HEX)
    const sas = deriveSASFromECDH(bridgeSec, iosPub)
    expect(sas.length).toBe(4)
    expect(toHex(sas)).toBe(EXPECTED_SAS_FROM_ECDH_HEX)
  })

  it('SAS is also commutative', () => {
    const bridgeSec = hex(FIXED_BRIDGE_SECRET_HEX)
    const bridgePub = hex(FIXED_BRIDGE_PUBLIC_HEX)
    const iosSec = hex(FIXED_IOS_SECRET_HEX)
    const iosPub = hex(FIXED_IOS_PUBLIC_HEX)
    const a = deriveSASFromECDH(bridgeSec, iosPub)
    const b = deriveSASFromECDH(iosSec, bridgePub)
    expect(toHex(a)).toBe(toHex(b))
  })

  it('keypair sizes are 32/32', () => {
    const kp = generateKeypair()
    expect(kp.publicKey.length).toBe(X25519_KEY_BYTES)
    expect(kp.secretKey.length).toBe(X25519_KEY_BYTES)
  })

  it('two distinct pairings derive different install_keys', () => {
    const k1 = generateKeypair()
    const k2 = generateKeypair()
    const k3 = generateKeypair()
    const a = deriveInstallKeyFromECDH(k1.secretKey, k2.publicKey)
    const b = deriveInstallKeyFromECDH(k1.secretKey, k3.publicKey)
    expect(toHex(a)).not.toBe(toHex(b))
  })
})

// ─── End-to-end: pair → derive → encrypt → decrypt ──────────────────

describe('full flow', () => {
  it('mirrors a complete pairing → message round-trip', () => {
    const bridge = generateKeypair()
    const ios = generateKeypair()
    const installKeyAtBridge = deriveInstallKeyFromECDH(bridge.secretKey, ios.publicKey)
    const installKeyAtIos = deriveInstallKeyFromECDH(ios.secretKey, bridge.publicKey)
    expect(toHex(installKeyAtBridge)).toBe(toHex(installKeyAtIos))

    const blobKey = deriveBlobKey(installKeyAtBridge, 'messages/m_abc')

    const plain = new TextEncoder().encode('agent reply with code')
    const ct = encryptSymmetric(plain, blobKey)
    const out = decryptSymmetric(ct, blobKey)
    expect(out).not.toBeNull()
    expect(new TextDecoder().decode(out!)).toBe('agent reply with code')
  })
})
